version: '2'

services:
    web:
        depends_on:
            - php
        container_name: web1
        hostname: ark-web1
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./files/web/conf/pterodactyl.conf:/etc/nginx/conf.d/pterodactyl.conf #originally in /etc/nginx/sites-available
            - ./files/web/conf/nginx.conf:/etc/nginx/nginx.conf #f00z - main nginx configuration file
            - ./files/web/conf/default.conf:/etc/nginx/conf.d/default.conf #f00z
            # - ./files/:/etc/nginx/sites-available/pterodactyl.conf
            # - ./files/:/etc/nginx/sites-enabled/pterodactyl.conf
            - shared:/var/www/pterodactyl/html/
        networks:
            - web-network-01
    php:
        depends_on:
            - sql
        container_name: php1
        hostname: ark-php1
        build: dockerfiles/php/
        #build: .
        #image: quay.io/xyelz/docker-pterodactyl-v3
        volumes:
            - ./files/php/conf/pterodactyl-worker.conf:/etc/supervisord.d/pterodactyl-worker.ini #f00z- tries to keep php artisan running
            - ./files/php/conf/php-fpm-worker.conf:/etc/supervisord.d/php-fpm-worker.ini #f00z - tries to keep php-fpm up and running
            - ./files/php/conf/www.conf:/etc/opt/remi/php70/php-fpm.d/www.conf #f00z
            - ./files/php/bin/entrypoint.sh:/var/www/html/entrypoint.sh #f00z - previously included as part of the PHP Dockerfile
            # - ./files/:/etc/supervisor/conf.d/pterodactyl-worker.conf
            - shared:/var/www/pterodactyl/html/
        environment:
            - "db_host=ark-sql1"
            - "db_port=3306"
            - "db_name=pterodb"
            - "db_user=ptero"
            - "db_pass=pterodbpassword"
            - "panel_url=ptero.home"
            - "timezone=America/New_York"
            - "email_driver=mail"
            - "panel_email=foo@bar"
            - "email_user="
            - "email_pass="
            - "email_domain="
            - "email_port="
            - "admin_email=xyelz@hotmail.com"
            - "admin_pass=PteroAdmin1"
            - "admin_stat=1"
        ports:
            - "9000:9000"
        networks:
            - web-network-01
    sql:
        container_name: sql1
        hostname: ark-sql1
        image: mariadb:latest
        command: mysqld
        volumes:
            # What is "dbdata" referring to here? A shared volume of some sort?
            - dbdata:/var/lib/mysql/
        environment:
            - "MYSQL_DATABASE=pterodb"
            - "MYSQL_ROOT_PASSWORD=pterosqlpassword"
            - "MYSQL_PASSWORD=pterodbpassword"
            - "MYSQL_USER=ptero"
        networks: web-network-01
        ports:
            - "3306:3306"
volumes:
    shared:
    dbdata:
networks:
    web-network-01:
        driver: bridge
        
